CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(254) NOT NULL UNIQUE,
    clave VARCHAR(200) NOT NULL,
    rol VARCHAR(10) NOT NULL CHECK (rol IN ('ADMIN', 'USER')),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS generos (
    id INT PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS peliculas (
    id INT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    genero_id INT NOT NULL REFERENCES generos(id),
    minutos INT NOT NULL CHECK (minutos > 0),
    clasificacion VARCHAR(10) NOT NULL,
    sinopsis VARCHAR(500) NOT NULL,
    estilo VARCHAR(30) NOT NULL,
    poster VARCHAR(80) NOT NULL,
    subtitulo VARCHAR(80) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS salas (
    id INT PRIMARY KEY,
    nombre VARCHAR(40) NOT NULL,
    aforo INT NOT NULL CHECK (aforo > 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS funciones (
    id INT PRIMARY KEY,
    pelicula_id INT NOT NULL REFERENCES peliculas(id),
    sala_id INT NOT NULL REFERENCES salas(id),
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    precio DECIMAL(10, 2) NOT NULL CHECK (precio >= 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 4) PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    funcion_id INT NOT NULL REFERENCES funciones(id),
    turno INT NOT NULL CHECK (turno > 0),
    precio DECIMAL(10, 2) NOT NULL CHECK (precio >= 0),
    fecha_compra DATE NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (funcion_id, turno)
);

CREATE TABLE IF NOT EXISTS compras (
    id VARCHAR(36) PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    funcion_id INT NOT NULL REFERENCES funciones(id),
    cantidad INT NOT NULL CHECK (cantidad > 0),
    total DECIMAL(10, 2) NOT NULL CHECK (total >= 0),
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tickets ALTER COLUMN usuario_id DROP NOT NULL;
ALTER TABLE compras ALTER COLUMN usuario_id DROP NOT NULL;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS invitado VARCHAR(36);

ALTER TABLE tickets ADD COLUMN IF NOT EXISTS asiento VARCHAR(6);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS compra_id VARCHAR(36) REFERENCES compras(id);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS asiento_vigente VARCHAR(6)
    GENERATED ALWAYS AS (CASE WHEN activo THEN asiento ELSE NULL END);
CREATE UNIQUE INDEX IF NOT EXISTS asiento_unico_por_funcion ON tickets (funcion_id, asiento_vigente);
